name: "CI"
on:
  schedule:
    - cron: "15 7 * * 1"
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    - '**.org'
    - '.dir-locals.el'

jobs:
  linux_x86:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [29.2, 29.3, 29.4, 30.1, release-snapshot, snapshot]
    steps:
    - uses: actions/checkout@v5
    - name: Setup Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Check emacs version
      run: make

  macos_arm:
    runs-on: macos-latest
    strategy:
      matrix:
        emacs_version: [29.2, 29.3, 29.4, 30.1, release-snapshot, snapshot]
    steps:
    - uses: actions/checkout@v5
    - name: Setup Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Check emacs version
      run: make
