name: testing literate emacs configuration
on:
    push:
        branches: [ main ]
        workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: set up emacs
              uses: purcell/setup-emacs@master
              with:
                  version: 30.1

            - name: check linux environment
              run: |
                  pwd
                  ls

