name: "CI"
on:
  push:

jobs:
  linux_x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Emacs
        uses: purcell/setup-emacs@v3.0
        with:
          version: 30.1
      - name: Check emacs version
        run: emacs --version

  macos_arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Emacs
        uses: purcell/setup-emacs@v3.0
        with:
          version: 30.1
      - name: Check emacs version
        run: emacs --version

